# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogTotal < Formula
  desc ""
  homepage ""
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.1/log_total_0.2.1_Darwin_64bit.tar.gz"
      sha256 "27e4149336a07c863c50453599ca1da7f96bde044afa74ee4b6718fa4533b18d"

      def install
        bin.install "log_total"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.1/log_total_0.2.1_Darwin_ARM64.tar.gz"
      sha256 "ce691af8ba330ffc9fcbd23f8d16597819c2fe28e0f4dbcbb67f81dcb7b865fe"

      def install
        bin.install "log_total"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.1/log_total_0.2.1_Linux_64bit.tar.gz"
      sha256 "cb80c5507ce6debb3c5b328bae6f93ffce4c8584c1fea6676200fdea58d7e074"

      def install
        bin.install "log_total"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.1/log_total_0.2.1_Linux_ARM64.tar.gz"
      sha256 "3d25536405c18daa7d5ab58f3193977c6f06ddd2bf5d7600a22e1ea7c77fee65"

      def install
        bin.install "log_total"
      end
    end
  end
end
