# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogTotal < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.3.0/log_total_0.3.0_Darwin_ARM64.tar.gz"
      sha256 "7686a3166ea1c8a74d5cafd8a2774fba8e6323644219b7b1208d0d224b3885ae"

      def install
        bin.install "log_total"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.3.0/log_total_0.3.0_Darwin_64bit.tar.gz"
      sha256 "2e70d68e49d4add73a66ea55211ef180417d5f30a8cdb079e75d53975e6d4a6e"

      def install
        bin.install "log_total"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.3.0/log_total_0.3.0_Linux_64bit.tar.gz"
      sha256 "89a1ff0c4150b71044c6037d61588184465d6e5dc2368ae29135002a235c3b6e"

      def install
        bin.install "log_total"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.3.0/log_total_0.3.0_Linux_ARM64.tar.gz"
      sha256 "ae989a4452189c2363ea511f452d0ba71c0f7d51989d6e5c180e650ce861bae2"

      def install
        bin.install "log_total"
      end
    end
  end
end
