# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogTotal < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.0/log_total_0.2.0_Darwin_64bit.tar.gz"
      sha256 "815f6d93a68e7396a0e4af1add29c5c404038d8349edb711fc5ebe458cb4fa49"

      def install
        bin.install "log_total"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.0/log_total_0.2.0_Darwin_ARM64.tar.gz"
      sha256 "53f4a233094b5171f02085cf54886ccc1adafcdca56b864005b2886c1c760a6a"

      def install
        bin.install "log_total"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.0/log_total_0.2.0_Linux_64bit.tar.gz"
      sha256 "f15ddd0181d55d94084df527d6c3c3074e7b7881f54a3f06d366eefbfc9569f9"

      def install
        bin.install "log_total"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n4rvs3/log_total/releases/download/v0.2.0/log_total_0.2.0_Linux_ARM64.tar.gz"
      sha256 "d4124a9b7f5161dcf0f5eecc311cefa527c83ff9bcb20348091b43666a640f2c"

      def install
        bin.install "log_total"
      end
    end
  end
end
